services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    container_name: peopleDesk-services
  # frontend services 
  frontend:
    build: 
      context: ./frontend
    ports:
    - 3000:3000

    env_file:
      - ./frontend/.env
    container_name: peopleDesk-frontend
